INSERT_POKEMON_POKEMON_INFO = """INSERT INTO POKEMON_INFO 
VALUES(%s,%s)"""


INSERT_INTO_TRAINERS_INFO = """ INSERT INTO Trainers_info VALUES (%s, %s, %s)"""

INSERT_INTO_TRAINERS_POKEMONS = """ INSERT INTO Trainers_pokemons VALUES (%s, %s)"""
